name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # This tells the action to explicitly fetch the latest SDK
          # and setup the build environment for all platforms
          combine: true
          
